[build]
  base = "game-pass-hero"
  command = "npm install && npm run build"
  publish = "game-pass-hero/.next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

